package com.brest.ericpol.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Equipment service. Represents a row in the &quot;app_Equipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.brest.ericpol.service.model.impl.EquipmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.brest.ericpol.service.model.impl.EquipmentImpl}.
 * </p>
 *
 * @author Viktor Kolbik
 * @see Equipment
 * @see com.brest.ericpol.service.model.impl.EquipmentImpl
 * @see com.brest.ericpol.service.model.impl.EquipmentModelImpl
 * @generated
 */
public interface EquipmentModel extends BaseModel<Equipment> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a equipment model instance should use the {@link Equipment} interface instead.
     */

    /**
     * Returns the primary key of this equipment.
     *
     * @return the primary key of this equipment
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this equipment.
     *
     * @param primaryKey the primary key of this equipment
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the equipment ID of this equipment.
     *
     * @return the equipment ID of this equipment
     */
    public long getEquipmentId();

    /**
     * Sets the equipment ID of this equipment.
     *
     * @param equipmentId the equipment ID of this equipment
     */
    public void setEquipmentId(long equipmentId);

    /**
     * Returns the modification of this equipment.
     *
     * @return the modification of this equipment
     */
    @AutoEscape
    public String getModification();

    /**
     * Sets the modification of this equipment.
     *
     * @param modification the modification of this equipment
     */
    public void setModification(String modification);

    /**
     * Returns the price of this equipment.
     *
     * @return the price of this equipment
     */
    public long getPrice();

    /**
     * Sets the price of this equipment.
     *
     * @param price the price of this equipment
     */
    public void setPrice(long price);

    /**
     * Returns the tank ID of this equipment.
     *
     * @return the tank ID of this equipment
     */
    public long getTankId();

    /**
     * Sets the tank ID of this equipment.
     *
     * @param tankId the tank ID of this equipment
     */
    public void setTankId(long tankId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Equipment equipment);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Equipment> toCacheModel();

    @Override
    public Equipment toEscapedModel();

    @Override
    public Equipment toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
