package com.brest.ericpol.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Tank service. Represents a row in the &quot;app_Tank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.brest.ericpol.service.model.impl.TankModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.brest.ericpol.service.model.impl.TankImpl}.
 * </p>
 *
 * @author Viktor Kolbik
 * @see Tank
 * @see com.brest.ericpol.service.model.impl.TankImpl
 * @see com.brest.ericpol.service.model.impl.TankModelImpl
 * @generated
 */
public interface TankModel extends BaseModel<Tank> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tank model instance should use the {@link Tank} interface instead.
     */

    /**
     * Returns the primary key of this tank.
     *
     * @return the primary key of this tank
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this tank.
     *
     * @param primaryKey the primary key of this tank
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the tank ID of this tank.
     *
     * @return the tank ID of this tank
     */
    public long getTankId();

    /**
     * Sets the tank ID of this tank.
     *
     * @param tankId the tank ID of this tank
     */
    public void setTankId(long tankId);

    /**
     * Returns the number of this tank.
     *
     * @return the number of this tank
     */
    @AutoEscape
    public String getNumber();

    /**
     * Sets the number of this tank.
     *
     * @param number the number of this tank
     */
    public void setNumber(String number);

    /**
     * Returns the modification of this tank.
     *
     * @return the modification of this tank
     */
    @AutoEscape
    public String getModification();

    /**
     * Sets the modification of this tank.
     *
     * @param modification the modification of this tank
     */
    public void setModification(String modification);

    /**
     * Returns the price of this tank.
     *
     * @return the price of this tank
     */
    public long getPrice();

    /**
     * Sets the price of this tank.
     *
     * @param price the price of this tank
     */
    public void setPrice(long price);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Tank tank);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Tank> toCacheModel();

    @Override
    public Tank toEscapedModel();

    @Override
    public Tank toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
