package com.brest.ericpol.service.model.impl;

import com.brest.ericpol.service.model.Equipment;
import com.brest.ericpol.service.model.EquipmentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Equipment service. Represents a row in the &quot;app_Equipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.brest.ericpol.service.model.EquipmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EquipmentImpl}.
 * </p>
 *
 * @author Viktor Kolbik
 * @see EquipmentImpl
 * @see com.brest.ericpol.service.model.Equipment
 * @see com.brest.ericpol.service.model.EquipmentModel
 * @generated
 */
public class EquipmentModelImpl extends BaseModelImpl<Equipment>
    implements EquipmentModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a equipment model instance should use the {@link com.brest.ericpol.service.model.Equipment} interface instead.
     */
    public static final String TABLE_NAME = "app_Equipment";
    public static final Object[][] TABLE_COLUMNS = {
            { "equipmentId", Types.BIGINT },
            { "modification", Types.VARCHAR },
            { "price", Types.BIGINT },
            { "tankId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table app_Equipment (equipmentId LONG not null primary key,modification VARCHAR(75) null,price LONG,tankId LONG)";
    public static final String TABLE_SQL_DROP = "drop table app_Equipment";
    public static final String ORDER_BY_JPQL = " ORDER BY equipment.equipmentId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY app_Equipment.equipmentId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.brest.ericpol.service.model.Equipment"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.brest.ericpol.service.model.Equipment"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.brest.ericpol.service.model.Equipment"),
            true);
    public static long MODIFICATION_COLUMN_BITMASK = 1L;
    public static long PRICE_COLUMN_BITMASK = 2L;
    public static long TANKID_COLUMN_BITMASK = 4L;
    public static long EQUIPMENTID_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.brest.ericpol.service.model.Equipment"));
    private static ClassLoader _classLoader = Equipment.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Equipment.class
        };
    private long _equipmentId;
    private String _modification;
    private String _originalModification;
    private long _price;
    private long _originalPrice;
    private boolean _setOriginalPrice;
    private long _tankId;
    private long _originalTankId;
    private boolean _setOriginalTankId;
    private long _columnBitmask;
    private Equipment _escapedModel;

    public EquipmentModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _equipmentId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setEquipmentId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _equipmentId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Equipment.class;
    }

    @Override
    public String getModelClassName() {
        return Equipment.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("equipmentId", getEquipmentId());
        attributes.put("modification", getModification());
        attributes.put("price", getPrice());
        attributes.put("tankId", getTankId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long equipmentId = (Long) attributes.get("equipmentId");

        if (equipmentId != null) {
            setEquipmentId(equipmentId);
        }

        String modification = (String) attributes.get("modification");

        if (modification != null) {
            setModification(modification);
        }

        Long price = (Long) attributes.get("price");

        if (price != null) {
            setPrice(price);
        }

        Long tankId = (Long) attributes.get("tankId");

        if (tankId != null) {
            setTankId(tankId);
        }
    }

    @Override
    public long getEquipmentId() {
        return _equipmentId;
    }

    @Override
    public void setEquipmentId(long equipmentId) {
        _equipmentId = equipmentId;
    }

    @Override
    public String getModification() {
        if (_modification == null) {
            return StringPool.BLANK;
        } else {
            return _modification;
        }
    }

    @Override
    public void setModification(String modification) {
        _columnBitmask |= MODIFICATION_COLUMN_BITMASK;

        if (_originalModification == null) {
            _originalModification = _modification;
        }

        _modification = modification;
    }

    public String getOriginalModification() {
        return GetterUtil.getString(_originalModification);
    }

    @Override
    public long getPrice() {
        return _price;
    }

    @Override
    public void setPrice(long price) {
        _columnBitmask |= PRICE_COLUMN_BITMASK;

        if (!_setOriginalPrice) {
            _setOriginalPrice = true;

            _originalPrice = _price;
        }

        _price = price;
    }

    public long getOriginalPrice() {
        return _originalPrice;
    }

    @Override
    public long getTankId() {
        return _tankId;
    }

    @Override
    public void setTankId(long tankId) {
        _columnBitmask |= TANKID_COLUMN_BITMASK;

        if (!_setOriginalTankId) {
            _setOriginalTankId = true;

            _originalTankId = _tankId;
        }

        _tankId = tankId;
    }

    public long getOriginalTankId() {
        return _originalTankId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Equipment.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Equipment toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Equipment) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        EquipmentImpl equipmentImpl = new EquipmentImpl();

        equipmentImpl.setEquipmentId(getEquipmentId());
        equipmentImpl.setModification(getModification());
        equipmentImpl.setPrice(getPrice());
        equipmentImpl.setTankId(getTankId());

        equipmentImpl.resetOriginalValues();

        return equipmentImpl;
    }

    @Override
    public int compareTo(Equipment equipment) {
        long primaryKey = equipment.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Equipment)) {
            return false;
        }

        Equipment equipment = (Equipment) obj;

        long primaryKey = equipment.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        EquipmentModelImpl equipmentModelImpl = this;

        equipmentModelImpl._originalModification = equipmentModelImpl._modification;

        equipmentModelImpl._originalPrice = equipmentModelImpl._price;

        equipmentModelImpl._setOriginalPrice = false;

        equipmentModelImpl._originalTankId = equipmentModelImpl._tankId;

        equipmentModelImpl._setOriginalTankId = false;

        equipmentModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Equipment> toCacheModel() {
        EquipmentCacheModel equipmentCacheModel = new EquipmentCacheModel();

        equipmentCacheModel.equipmentId = getEquipmentId();

        equipmentCacheModel.modification = getModification();

        String modification = equipmentCacheModel.modification;

        if ((modification != null) && (modification.length() == 0)) {
            equipmentCacheModel.modification = null;
        }

        equipmentCacheModel.price = getPrice();

        equipmentCacheModel.tankId = getTankId();

        return equipmentCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(9);

        sb.append("{equipmentId=");
        sb.append(getEquipmentId());
        sb.append(", modification=");
        sb.append(getModification());
        sb.append(", price=");
        sb.append(getPrice());
        sb.append(", tankId=");
        sb.append(getTankId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(16);

        sb.append("<model><model-name>");
        sb.append("com.brest.ericpol.service.model.Equipment");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>equipmentId</column-name><column-value><![CDATA[");
        sb.append(getEquipmentId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modification</column-name><column-value><![CDATA[");
        sb.append(getModification());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>price</column-name><column-value><![CDATA[");
        sb.append(getPrice());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>tankId</column-name><column-value><![CDATA[");
        sb.append(getTankId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
