package com.brest.ericpol.service.model.impl;

import com.brest.ericpol.service.model.Tank;
import com.brest.ericpol.service.service.TankLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Tank service. Represents a row in the &quot;app_Tank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TankImpl}.
 * </p>
 *
 * @author Viktor Kolbik
 * @see TankImpl
 * @see com.brest.ericpol.service.model.Tank
 * @generated
 */
public abstract class TankBaseImpl extends TankModelImpl implements Tank {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tank model instance should use the {@link Tank} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TankLocalServiceUtil.addTank(this);
        } else {
            TankLocalServiceUtil.updateTank(this);
        }
    }
}
